# To allow #/ or #: comments.
Layout/LeadingCommentSpace:
  Enabled: false

# This is flaky.
Layout/RescueEnsureAlignment:
  Enabled: false

# Too much noise.
Layout/LineLength:
  Enabled: false

# Too much noise.
Style/FrozenStringLiteralComment:
  Enabled: false

# Don't see the need.
Style/NumericLiterals:
  Enabled: false

# Don't see the need for these, too much noise.
Style/PerlBackrefs:
  Enabled: false

# I prefer this approach.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Consistency with above.
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# I prefer this approach.
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
